version: '3'

services:
  backend:
    build: ./be-app
    volumes:
      - ./be-app:/app
    ports:
      - 8080:8080
    container_name: portfolio_backend
  
  frontend:
    build: ./fe-app
    volumes:
      - ./fe-app:/app
    container_name: portfolio_frontend
    ports:
      - 3000:3000